//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesGaranties.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Garanties = new HashSet<Garantie>();
            this.Preniums = new HashSet<Prenium>();
            this.webpages_Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string Mail { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Langue { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<Garantie> Garanties { get; set; }
        public virtual ICollection<Prenium> Preniums { get; set; }
        public virtual ICollection<Role> webpages_Roles { get; set; }
    }
}
